server:
  port: 8888
spring:
  application:
    name: CLOUD-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/niket17590/cloud-config-repo.git
          search-paths: '{application}'
          default-label: master
management:
  endpoints:
    web:
      exposure:
        include: health,refresh
