INSERT INTO EMPLOYEE (EMP_ID,EMP_NAME,EMP_SURNAME,EMP_CITY) VALUES(1,'Niket','Agrawal','Pune');
INSERT INTO EMPLOYEE (EMP_ID,EMP_NAME,EMP_SURNAME,EMP_CITY) VALUES(2,'Pratish','Mishra','Indore');
INSERT INTO EMPLOYEE (EMP_ID,EMP_NAME,EMP_SURNAME,EMP_CITY) VALUES(3,'Roma','Wali','Dehradun');